/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Indian_Consensus_System_Git_Assignment;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
